name: Build and Analyze with SonarQube
on: push
jobs:
  build-and-analyze:
    runs-on: ubuntu-latest
    steps:
- name: Checkout code
      uses: actions/checkout@v2
    - name: Set up JDK 23
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: 23
    - name: Cache SonarQube dependencies
      uses: actions/cache@v2
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar-cache
        restore-keys: |
          ${{ runner.os }}-sonar-cache
    - name: Run SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      with:
        projectBaseDir: .
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}